#!/usr/bin/env python3
"""Router admin helper — detect common gateway URLs and export blocks."""

from __future__ import annotations

import socket
import webbrowser
from pathlib import Path
from typing import List, Optional, Tuple

SCRIPT_DIR = Path(__file__).resolve().parent

COMMON_PATHS = (
    "/",
    "/login.html",
    "/login.asp",
    "/index.html",
    "/webpages/login.html",
    "/cgi-bin/",
    "/admin/",
)


def probe_gateway_admin(gateway: str, timeout: float = 0.8) -> List[str]:
    """Return likely reachable admin base URLs for the gateway."""
    if not gateway:
        return []
    found: List[str] = []
    for scheme, port in (("http", 80), ("https", 443), ("http", 8080)):
        try:
            with socket.create_connection((gateway, port), timeout=timeout):
                found.append(f"{scheme}://{gateway}:{port}/" if port not in (80, 443) else f"{scheme}://{gateway}/")
        except OSError:
            continue
    return found


def open_gateway_admin(gateway: str) -> Tuple[bool, str]:
    urls = probe_gateway_admin(gateway)
    if not urls:
        return False, f"No HTTP(S) admin interface detected on {gateway}"
    url = urls[0]
    try:
        webbrowser.open(url, new=2)
    except Exception:
        pass
    return True, f"Opened {url}"


def export_router_blocks(ips: List[str], path: Optional[Path] = None) -> Path:
    path = path or (SCRIPT_DIR / "router_block_candidates.txt")
    lines = [
        "# Paste these into your router firewall / parental controls / deny list",
        "# Generated by Network Guard — Pilisi W — 2026",
        "# Formats: one IP per line (most routers) + CSV for some UIs",
        "",
        "# --- one per line ---",
    ]
    clean = sorted({ip.strip() for ip in ips if ip.strip()})
    lines.extend(clean)
    lines.append("")
    lines.append("# --- CSV ---")
    lines.append(",".join(clean))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
